version: "2"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "80:3000"
    command: "npm start"
    networks:
      - lealinon
  mongo:
    image: mongo
    restart: always
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: pass
    networks:
      - lealinon
    ports:
      - "27017:27017"
    volumes:
      - ./data/lealinon/db/:/data/db
      - ./data/lealinon/dump/:/dump
networks:
  lealinon:
    driver: bridge